### ISSUE TITLE
How do I search this database?

### ISSUE THREAD

**Issue by fluffynukeit** [DavHau/pypi-deps-db#1]
If I get the mach-nix message that my pacakge "is not available from any of the selected providers {'sdist', 'nixpkgs', 'wheel'} for the selected python version", how do I search this database to see for which python versions the database does have the package, if any?  When I use the github "Search or jump to" box, I get no hits in code.  For example, both "keras" and "keras extension:json" return no hits.  Thanks.

Edit: the best solution for now, as far as I can tell, is to download the repo as a zip or clone it, then use a search function local to my computer.  It's a slightly bothersome step but not big enough to be worth fixing.  Will close the issue.

**Comment by DavHau** [comment]
I think it would be nice if there was a website to browse the data, but things like that are not high up on my priority list right now. Contributions are always welcome of course.
